#!/usr/bin/env python3
"""
Interactive Configuration Setup
--------------------------------
Automatically configure the application on first run.
"""
import secrets
import sys
from pathlib import Path


def generate_secret_key():
    """Generate a secure random secret key."""
    return secrets.token_hex(32)


def get_users():
    """Prompt for user names."""
    print("\n👥 User Configuration")
    print("=" * 50)
    print("Enter the names of people to track expenses for.")
    print("Examples: Alice, Bob | John, Jane | You, Partner")
    print()
    
    while True:
        users_input = input("Enter user names (comma-separated): ").strip()
        if not users_input:
            print("❌ Please enter at least one user name.")
            continue
        
        users = [name.strip() for name in users_input.split(",")]
        users = [name for name in users if name]  # Remove empty strings
        
        if len(users) < 1:
            print("❌ Please enter at least one user name.")
            continue
        
        print(f"\n✅ Users configured: {', '.join(users)}")
        confirm = input("Is this correct? (y/n): ").strip().lower()
        if confirm in ('y', 'yes'):
            return users


def get_password():
    """Prompt for application password."""
    print("\n🔐 Password Configuration")
    print("=" * 50)
    print("Set a password to access the application.")
    print("Choose something secure but memorable.")
    print()
    
    while True:
        password = input("Enter app password: ").strip()
        if not password:
            print("❌ Password cannot be empty.")
            continue
        
        if len(password) < 4:
            print("⚠️  Password is very short. Consider using a longer password.")
            confirm = input("Continue anyway? (y/n): ").strip().lower()
            if confirm not in ('y', 'yes'):
                continue
        
        password_confirm = input("Confirm password: ").strip()
        if password != password_confirm:
            print("❌ Passwords don't match. Try again.\n")
            continue
        
        return password


def get_optional_settings():
    """Ask if user wants to customize optional settings."""
    print("\n⚙️  Optional Settings")
    print("=" * 50)
    print("Do you want to customize expense categories?")
    print("(Default categories will be used if you skip this)")
    print()
    
    customize = input("Customize categories? (y/n, default: n): ").strip().lower()
    
    settings = {}
    
    if customize in ('y', 'yes'):
        print("\n📋 Utility Types")
        print("Current defaults: Electricity, Gas, Water, Internet")
        custom_utilities = input("Enter utility types (comma-separated, or press Enter to use defaults): ").strip()
        if custom_utilities:
            settings['UTILITY_TYPES'] = [u.strip() for u in custom_utilities.split(",") if u.strip()]
        
        print("\n💰 Fixed Expense Types")
        print("Current defaults: Rent, Internet")
        custom_fixed = input("Enter fixed expense types (comma-separated, or press Enter to use defaults): ").strip()
        if custom_fixed:
            settings['FIXED_EXPENSE_TYPES'] = [f.strip() for f in custom_fixed.split(",") if f.strip()]
    
    return settings


def create_config_file(secret_key, password, users, optional_settings):
    """Create the config_private.py file."""
    config_path = Path(__file__).parent / "config_private.py"
    
    config_content = f'''"""
Private Configuration
----------------------
Personal configuration - NOT tracked in git.
Auto-generated by setup script.
"""

# Security Settings
SECRET_KEY = "{secret_key}"
APP_PASSWORD = "{password}"

# User Configuration
USERS = {users!r}
'''
    
    if 'UTILITY_TYPES' in optional_settings:
        config_content += f'\n# Custom Utility Types\nUTILITY_TYPES = {optional_settings["UTILITY_TYPES"]!r}\n'
    
    if 'FIXED_EXPENSE_TYPES' in optional_settings:
        config_content += f'\n# Custom Fixed Expense Types\nFIXED_EXPENSE_TYPES = {optional_settings["FIXED_EXPENSE_TYPES"]!r}\n'
    
    with open(config_path, 'w') as f:
        f.write(config_content)
    
    return config_path


def run_interactive_setup():
    """Run the interactive setup process."""
    print("\n" + "=" * 50)
    print("  💰 Expenses Tracker - Initial Setup")
    print("=" * 50)
    print()
    print("This wizard will help you configure the application.")
    print("Your settings will be saved to config_private.py")
    print()
    
    # Generate secret key automatically
    print("🔑 Generating secure secret key... ", end="")
    secret_key = generate_secret_key()
    print("✅ Done")
    
    # Get required settings
    users = get_users()
    password = get_password()
    
    # Get optional settings
    optional_settings = get_optional_settings()
    
    # Create config file
    print("\n📝 Creating Configuration")
    print("=" * 50)
    config_path = create_config_file(secret_key, password, users, optional_settings)
    print(f"✅ Configuration saved to: {config_path}")
    
    # Summary
    print("\n✨ Setup Complete!")
    print("=" * 50)
    print(f"👥 Users: {', '.join(users)}")
    print(f"🔐 Password: {'*' * len(password)}")
    print(f"🔑 Secret Key: Generated securely")
    if optional_settings:
        print(f"⚙️  Custom settings: {len(optional_settings)} configured")
    print()
    
    return True


def check_and_setup():
    """Check if setup is needed and run if necessary."""
    config_path = Path(__file__).parent / "config_private.py"
    
    if config_path.exists():
        return True  # Already configured
    
    print("\n⚠️  Configuration file not found!")
    print()
    print("Would you like to run the setup wizard now?")
    print("(This will create config_private.py with your settings)")
    print()
    
    response = input("Run setup wizard? (y/n): ").strip().lower()
    if response in ('y', 'yes'):
        return run_interactive_setup()
    else:
        print("\n❌ Setup cancelled.")
        print("\nTo configure manually:")
        print("  1. Copy config_private.py.template to config_private.py")
        print("  2. Edit config_private.py with your settings")
        print("  3. Run the application again")
        return False


if __name__ == "__main__":
    if run_interactive_setup():
        print("\n🚀 You can now run the application with: python run.py")
        sys.exit(0)
    else:
        sys.exit(1)
